<a href="https://colab.research.google.com/github/purity-muchiri/dsc-running-jupyter-locally-lab/blob/master/groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1.0,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S
1,2.0,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C
2,3.0,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4.0,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1386,839.0,0.0,?,"Rush, Mr. Alfred George John",male,47.0,0.0,4.0,113510,12.8750,B79,C
1387,839.0,1.0,2,"Skoog, Master. Harald",female,17.0,5.0,5.0,2671,17.4000,E49,NaN
1388,839.0,0.0,?,"Slocovski, Mr. Selman Francis",male,47.0,8.0,4.0,239854,7.0500,B49,NaN
1389,839.0,1.0,?,"Glynn, Miss. Mary Agatha",male,48.0,1.0,0.0,36866,8.6625,F G63,C
1390,839.0,0.0,?,"Sobey, Mr. Samuel James Hayden",male,14.5,3.0,4.0,2672,108.9000,C148,S

In [14]:
avg_fare_class=df.groupby("Pclass")["Fare"].mean()
avg_fare_class

Pclass
1    67.452418
2    27.788990
3    16.509801
?    37.366526
Name: Fare, dtype: float64

In [5]:
gender_survived_most=df.groupby("Sex")["Survived"].sum()
gender_survived_most

Sex
female    322.0
male      208.0
Name: Survived, dtype: float64

In [13]:
avg_fare=df.groupby(["Pclass","Sex"])["Fare"].mean()
avg_fare

Pclass  Sex
1       female    84.416536
        male      55.348805
2       female    26.972406
        male      28.431720
3       female    19.908623
        male      15.158895
?       female    49.604234
        male      28.543993
Name: Fare, dtype: float64

In [17]:
multiple_stats=df.groupby("Pclass").describe()
multiple_stats

       PassengerId                                                             \
             count        mean         std   min     25%    50%    75%    max
Pclass
1            305.0  587.216393  271.519613   2.0  340.00  672.0  839.0  890.0
2            277.0  588.054152  277.521420  10.0  345.00  696.0  839.0  887.0
3            661.0  427.434191  316.784929   1.0  109.00  426.0  761.0  891.0
?            148.0  733.513514  210.150755  26.0  753.75  839.0  839.0  889.0

       Survived            ... Parch        Fare                             \
          count      mean  ...   75%  max  count       mean        std  min
Pclass                     ...
1         305.0  0.573770  ...   2.0  6.0  305.0  67.452418  72.275465  0.0
2         277.0  0.465704  ...   2.0  6.0  277.0  27.788990  33.556691  0.0
3         661.0  0.245083  ...   1.0  6.0  661.0  16.509801  28.808145  0.0
?         148.0  0.432432  ...   4.0  6.0  148.0  37.366526  44.712945  0.0


             25%      50%      75%       max
Pclass
1       26.55000  51.8625  82.1708  512.3292
2       12.28750  15.0500  27.0000  247.5208
3        7.25000   7.9250  15.5000  512.3292
?        9.44375  20.3875  46.9500  247.5208

[4 rows x 48 columns]

In [23]:
multiple_stats=df.groupby("Pclass").agg({
  # Average and median age per class
    "Fare": ["mean", "median","min","max","count"]  # Average and total fare per class
})


multiple_stats

             Fare
             mean   median  min       max count
Pclass
1       67.452418  51.8625  0.0  512.3292   305
2       27.788990  15.0500  0.0  247.5208   277
3       16.509801   7.9250  0.0  512.3292   661
?       37.366526  20.3875  0.0  247.5208   148